Commit

diff --git a/.github/workflows/docker-publication.yml b/.github/workflows/docker-publication.yml
--- a/.github/workflows/docker-publication.yml
+++ b/.github/workflows/docker-publication.yml
@@ -1,35 +1,46 @@
 name: Docker Publication
 
+
 on:
   push:
     branches:
-      - main 
+      - main
 
 jobs:
-  build-and-test:
+  docker:
     runs-on: ubuntu-latest
-
     steps:
-      # Vérification du dépôt
       - name: Check out repository code
         uses: actions/checkout@v4
-
-
-      - name: Set up Node.js
-        uses: actions/setup-node@v3
+      
+      #Connexion à Docker Hub
+      - name: Log in to Docker Hub
+        uses: docker/login-action@v2
         with:
-          node-version: '18'
+          username: ${{ secrets.DOCKER_USERNAME }}
+          password: ${{ secrets.DOCKER_PASSWORD }}
+  
+        # Connexion au GitHub Container Registry
+      - name: Log in to GitHub Container Registry
+        uses: docker/login-action@v2
+        with:
+          registry: ghcr.io
+          username: ${{ github.actor }}
+          password: ${{ secrets.GHCR_TOKEN }}
+      # Construction de l’image du Docker
+      - name: Build Docker image
+        run: |
+          docker build -t myapp:${{ github.sha }} . || { echo "Docker build failed"; exit 1; }
 
-      # dépendances
-      - name: Install dependencies
-        run: npm install
-
-      # compilation de l'application
-      - name: Build the application
-        run: npm run build  
-
-      # exécution des tests unitaires
-      - name: Run unit tests
-        run: npm test
-        env:
-          CI: true  
+      - name: Tag Docker images
+        run: |
+          docker tag myapp:${{ github.sha }} mydockerhubuser/myapp:latest || { echo "Tagging failed"; exit 1; }
+          docker tag myapp:${{ github.sha }} ghcr.io/${{ github.repository }}/myapp:latest || { echo "Tagging failed"; exit 1; }
+      # Publication de l’image sur Docker Hub
+      - name: Push Docker image to Docker Hub
+        run: |
+          docker push mydockerhubuser/myapp:latest || { echo "Push to Docker Hub failed"; exit 1; }
+      # Publication de l’image sur GHCR 
+      - name: Push Docker image to GitHub Container Registry
+        run: |
+          docker push ghcr.io/${{ github.repository }}/myapp:latest || { echo "Push to GHCR failed"; exit 1; }
